version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: linkup-postgres
    environment:
      POSTGRES_DB: linkup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - linkup-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: linkup-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - linkup-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LinkUp Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: linkup-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: linkup
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 8080
      HOST: 0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - linkup-network
    restart: unless-stopped

  # LinkUp Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: linkup-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8080
      REACT_APP_WS_URL: ws://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - linkup-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: linkup-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - linkup-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  linkup-network:
    driver: bridge
